default: &default
  # Heruko
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # local
  # adapter: postgresql
  # encoding: unicode
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: postgres  
  # password: LearnIt@1  
  # host: localhost
  # port: 5432

development:
  <<: *default
  # heruko
  database: postgresql
  # local
  # database: clothcartel  

test:
  <<: *default
  # heruko
  database: postgresql
  # local
  # database: clothcartel  


production:
  <<: *default
  # Heruko
  # database: from Heruko
  # host: from Heruko
  # username: from Heruko  
  # password: <%= ENV["from Heruko"] %> 
  # port: 5432
  # local
  # database: clothcartel
  # password: <%= ENV["LearnIt@1"] %> 
